# Generated by Django 4.0.6 on 2022-07-24 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.BigAutoField(db_column='banner_id', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'db_table': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(db_column='cart_id', editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complit', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('is_in_order', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(db_column='category_id', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(db_column='product_id', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('marked_price', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('warranty', models.CharField(blank=True, max_length=300, null=True)),
                ('return_policy', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('file_id', models.BigAutoField(db_column='file_id', editable=False, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=150)),
                ('fileDesc', models.CharField(max_length=150)),
                ('myfile', models.FileField(upload_to='uploads/')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Uploads',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_id', models.BigAutoField(db_column='shipping_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('destinationtype', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Shipping_Address',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('size_id', models.BigAutoField(db_column='size_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sizes', models.CharField(choices=[('no sizes', 'no sizes'), ('uk=4', 'uk-4'), ('uk-5', 'uk-5'), ('uk-6', 'uk-6'), ('uk-7', 'uk-7'), ('uk-8', 'uk-8'), ('uk-9', 'uk-9'), ('uk-10', 'uk-10')], default='no sizes', max_length=100)),
                ('Product', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'db_table': 'Products_Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.BigAutoField(db_column='image_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='Productimages/')),
                ('product', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'db_table': 'Products_Images',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('color_id', models.BigAutoField(db_column='color_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('colors', models.CharField(choices=[('no colors', 'no colors'), ('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White')], default='no colors', max_length=20)),
                ('Product', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.product')),
            ],
            options={
                'db_table': 'Products_Colors',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(db_column='order_id', editable=False, primary_key=True, serialize=False)),
                ('ordered_by', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20)),
                ('payment_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress')),
                ('cart', models.OneToOneField(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
            ],
            options={
                'db_table': 'Product_Orders',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('cartitem_id', models.BigAutoField(db_column='cartitem_id', editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.PositiveBigIntegerField(default=100)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('color', models.ForeignKey(default='no_color', on_delete=django.db.models.deletion.CASCADE, to='store.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('size', models.ForeignKey(default='no_sizes', on_delete=django.db.models.deletion.CASCADE, to='store.productsize')),
            ],
            options={
                'db_table': 'Cart_Items',
            },
        ),
    ]
